version: "3"

services:
  app-no-balancer:
    image: docker.io/node:lts
    container_name: app-no-balancer
    build: ./
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3030:3001
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_PASS=password
      - DB_NAME=debit_db
      - DB_HOST=db_mysql
      - DB_PORT=3306
      - NODE_ENV=development
    depends_on:
      db_mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030" ]
      timeout: 10s
      retries: 5

  db_mysql:
    image: docker.io/mysql:8.0.23
    restart: always
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores

networks:
  # Rede padrão, criada automaticamente
  default:
    # Dá um nome específico à rede padrão
    name: project_mysql
